resources:
  - name: demo_gitRepo
    type: GitRepo
    configuration:
      path: shimib/Horae
      gitProvider: Github
  - name: gitRepo_code
    type: GitRepo
    configuration:
      path: shimib/project-examples
      gitProvider: Github
      branches:
        include: eplus-v2-orbitera
  - name: gradleBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: gradle_demo
      buildNumber: ${run_number}
  - name:       npm_fileSpec
    type:       FileSpec
    configuration:     
      sourceArtifactory:    artifactory
      pattern:              team1-npm-dev-us/angular-animate/-/angular-animate-1.4.14.tgz
      target:               npm_results/
      buildName:            npm_build   # optional
      buildNumber:          ${run_number}
      
pipelines:
  - name: init_environment
    steps:
    - name: create_scaffholding
      type: Bash
      configuration:
       inputResources:
        - name: demo_gitRepo
          trigger: false
       integrations:
        - name: Artifactory
      execution:
       onStart:
        - curl -fL https://getcli.jfrog.io | sh
        - sudo apt-get install -y jq
        - cp jfrog  `which jfrog`
        - retry_command jfrog rt config --url $int_Artifactory_url --user
          $int_Artifactory_user --apikey $int_Artifactory_apikey
          --interactive=false
        - "cd ${res_demo_gitRepo_resourcePath}"
        - "./scripts/create_entities.sh"
